name = "backend"
compatibility_date = "2024-08-31"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZmQ0ZDUwOTgtYzNhYy00NjUzLWExMGMtZTcwZmZmODgyYTdmIiwidGVuYW50X2lkIjoiMTkzYjRhZTkzOTA5YzkyYjllYzAzNjhjZTlmNmM5ODQyZjkxMGI4ZTFmYzVmZDYyODA2NDAzYzc3ZmNkZDc5YSIsImludGVybmFsX3NlY3JldCI6IjczZGE0YzAzLTM4NDAtNDZmYy1iOTg4LTc1OWM3NzJjOTJiOSJ9.OmSFMTO5GWSe1a9L7u94Ob-0yJirGkbu7SPsaR-E48k"


# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"